In [3]:
from __future__ import division, print_function, absolute_import
# To fix "AttributeError: module 'tensorflow' has no attribute 'placeholder'"
# Cf https://github.com/theislab/scgen/issues/14
#import tensorflow as tf 
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
import numpy as np
import os
from numpy import savetxt #to save numpy array to a file
os.environ["CUDA_VISIBLE_DEVICES"] = "1"

Instructions for updating:
non-resource variables are not supported in the long term


In [38]:
tf.__version__

'2.3.0'

In [15]:
def read_data(data_path):
    data = []
    # 1.txt
    file_names = os.listdir(data_path)
    file_names.sort(key=lambda x:int(x[:-4]))
    for file_name in file_names:
        file_path = os.path.join(data_path, file_name)
        signal_data = np.loadtxt(file_path)
        data.append(signal_data)
    data = np.array(data).transpose(0, 2, 1)
    
    d_shape = data.shape
    return data.reshape(d_shape[0], 1, d_shape[1], d_shape[2])

def read_label(data_path):
    data = []
    # 1.txt
    file_names = os.listdir(data_path)
    file_names.sort(key=lambda x:int(x[:-10]))
    for file_name in file_names:
        file_path = os.path.join(data_path, file_name)
        signal_data = np.loadtxt(file_path)
        data.append(signal_data)
    return np.array(data)

In [21]:
#train_data_path = "../data//train_new//train_data"
#train_label_path = "..//data//train_new//train_label"
train_data_path = "C:\\Users\\tpailhas\\MIASHS\\TER\\Parkinson\\Dataset\\Gait-Datasets-TIFS20\\Dataset7\\train\\train_data" 
train_label_path = "C:\\Users\\tpailhas\\MIASHS\\TER\\Parkinson\\Dataset\\Gait-Datasets-TIFS20\\Dataset7\\train\\train_label"

#test_data_path = "..//data//test//test_data"
#test_label_path = "..//data//test//test_label"
test_data_path = "C:\\Users\\tpailhas\\MIASHS\\TER\\Parkinson\\Dataset\\Gait-Datasets-TIFS20\\Dataset7\\test\\test_data" 
test_label_path = "C:\\Users\\tpailhas\\MIASHS\\TER\\Parkinson\\Dataset\\Gait-Datasets-TIFS20\\Dataset7\\test\\test_label"

print("***************************")
train_data = read_data(train_data_path).transpose(0, 2, 3, 1) # 519
train_label = read_label(train_label_path)
test_data = read_data(test_data_path).transpose(0, 2, 3, 1) # 519
test_label = read_label(test_label_path)

print(train_data.shape)
print(train_label.shape)
print(test_data.shape)
print(test_label.shape)

#np.save("train_data.npy", train_data) # save an array to a binary file in NumPy .npy format.
#np.save("train_label.npy", train_label)
#np.save("test_data.npy", test_data)
#np.save("test_label.npy", test_label)

***************************
*****signal_data *****************
[[ 5.94531   4.35938   7.28516   0.275635  0.072632  0.369629]
 [ 5.84766   4.39844   7.22656   0.197144  0.109314  0.319336]
 [ 5.94531   4.45703   7.1875    0.2771    0.160034  0.284424]
 ...
 [-8.80469   0.199829  3.1875    0.26001   0.399902 -0.308838]
 [-9.375     0.552734  5.01172  -0.176147  0.719727  1.20313 ]
 [-9.82031   1.20019   6.69922  -0.506348  1.25586   2.63477 ]]
*****signal_data *****************
[[-1.00547e+01  1.76856e+00  7.14844e+00 -6.59668e-01  1.71289e+00
   3.09375e+00]
 [-1.00781e+01  2.14063e+00  6.81641e+00 -6.48926e-01  1.99512e+00
   2.90039e+00]
 [-1.02344e+01  2.25977e+00  6.32422e+00 -7.72461e-01  2.04102e+00
   2.50977e+00]
 ...
 [-9.70313e+00 -3.23242e+00  3.43750e-01 -5.81055e-01 -2.26367e+00
  -2.86523e+00]
 [-8.68750e+00 -2.62500e+00  4.22363e-01  2.50732e-01 -1.78125e+00
  -2.76563e+00]
 [-9.01563e+00 -2.46680e+00  1.86890e-01 -2.56900e-03 -1.64453e+00
  -2.92188e+00]]
*****signal_da

*****signal_data *****************
[[-1.23516e+01  1.92578e+00 -1.22559e+00 -9.43359e-01 -7.78320e-01
  -1.57129e+00]
 [-1.09375e+01  1.00391e+00 -1.83301e+00  3.74756e-01 -1.36035e+00
  -1.74316e+00]
 [-9.66406e+00  3.69300e-03 -2.04883e+00  1.31934e+00 -1.88867e+00
  -1.56738e+00]
 ...
 [-9.49219e+00  9.25293e-01  1.83496e+00  1.06384e-01  2.20825e-01
   3.37402e-01]
 [-9.28906e+00  7.88086e-01  1.40332e+00  2.41943e-01  6.68950e-02
  -7.53170e-02]
 [-9.05469e+00  5.13672e-01  1.12793e+00  3.81836e-01 -1.66138e-01
  -2.80029e-01]]
*****signal_data *****************
[[ -8.84375    0.199829   0.716309   0.478027  -0.384033  -0.553223]
 [ -8.70313   -0.09436    0.363525   0.492432  -0.54248   -0.725098]
 [ -8.64844   -0.212036   0.128174   0.440918  -0.52832   -0.768555]
 ...
 [-11.4297     0.474365  -2.91211   -0.617188  -1.67773   -1.57422 ]
 [-10.4141    -0.820312  -2.73633    0.322021  -2.37891   -1.11816 ]
 [ -9.54688   -1.97754   -2.36328    0.948242  -2.82813   -0.59668 ]]
*****s

*****signal_data *****************
[[ 6.51563  -0.133667  4.12891  -0.265381  0.248779 -0.228638]
 [ 6.57422  -0.682617  4.69922  -0.165283 -0.240356  0.272217]
 [ 6.82813  -1.58496   5.81641   0.071716 -0.914062  1.11231 ]
 ...
 [ 9.08594   0.552734  5.46484   0.104797  0.284912  0.186646]
 [ 8.86719   0.67041   5.30469  -0.088745  0.322266  0.023773]
 [ 8.73438   0.905762  5.24609  -0.180786  0.446045 -0.028061]]
*****signal_data *****************
[[ 8.65625   1.12207   5.16797  -0.207397  0.529297 -0.085205]
 [ 8.55469   1.25879   5.1875   -0.244385  0.533203 -0.05249 ]
 [ 8.5       1.39648   5.26563  -0.242554  0.536621  0.020782]
 ...
 [ 8.85156  -3.625     6.52344   0.790527 -2.29297   1.0166  ]
 [ 9.5      -4.03516   7.1875    1.15039  -2.16406   1.34668 ]
 [10.1797   -3.97852   7.28516   1.46973  -1.68457   1.15625 ]]
*****signal_data *****************
[[ 8.43750e+00 -2.66406e+00  4.48047e+00 -2.85190e-02 -4.48730e-01
  -3.37402e-01]
 [ 9.14063e+00 -3.11523e+00  4.81641e+00  5.

*****signal_data *****************
[[-6.89844   9.25781   0.598633 -0.747559  0.789062 -0.408203]
 [-6.91797   9.71094  -0.26416  -0.61377   0.992188 -1.0166  ]
 [-7.05859   9.21875  -0.185669 -0.601074  0.401367 -0.750977]
 ...
 [-7.19531   6.75      3.36523  -0.538086 -0.701172 -0.265869]
 [-6.13672   6.51563   2.93359   0.416748 -0.749512 -0.557617]
 [-5.56641   6.73047   2.50195   0.788574 -0.427002 -0.791504]]
*****signal_data *****************
[[-5.3125    7.59375   1.81445   0.834961  0.348877 -1.18262 ]
 [-5.07422   7.71094   0.912598  0.855957  0.373291 -1.66797 ]
 [-5.23438   7.08594   0.18689   0.559082 -0.203491 -1.91504 ]
 ...
 [-5.48828   7.20313   1.28516   0.167358  0.301758  0.186279]
 [-5.27344   7.39844   1.16797   0.306396  0.398438  0.054932]
 [-5.01563   7.33984   1.44238   0.449219  0.271729  0.263672]]
*****signal_data *****************
[[-6.625    10.5938    2.59961   0.276123  3.14063   2.24609 ]
 [-5.76172  10.4375    3.93359   0.911133  2.38672   2.86328 ]
 

*****signal_data *****************
[[  2.90625   -3.85547   -1.09668    2.07617    3.69922    0.840332]
 [  3.0918    -3.47656    0.325684   1.80957    3.26172    1.80957 ]
 [  2.94336   -3.34766    0.890625   1.3291     2.71289    1.90039 ]
 ...
 [  1.93359  -10.4609     0.172363   0.724609  -0.738281  -0.026855]
 [  1.84277  -10.5547     0.775879   0.506836  -0.670898   0.461182]
 [  2.0918   -10.2656     1.02441    0.604492  -0.302979   0.568359]]
*****signal_data *****************
[[  2.58008   -9.23438    0.378174   0.874512   0.581055  -0.062622]
 [  2.3457    -9.1875    -0.249023   0.511719   0.503418  -0.551758]
 [  1.84668   -9.65625   -0.675293   0.011101   0.031006  -0.782715]
 ...
 [  2.62695  -10.4453     5.67578    1.98144   -0.705078   3.34766 ]
 [  5.64844   -9.49219    4.67969    4.00391    0.19812    1.88086 ]
 [  6.23438   -8.3125     1.16797    3.66992    1.10449   -1.30273 ]]
*****signal_data *****************
[[  5.33594   -7.58984   -0.612793   2.21875    1.46191

*****signal_data *****************
[[ -4.24219   -6.15625    4.34766   -1.08594    6.54688   -1.67871 ]
 [  7.23828    3.80664    4.85938    8.32031   13.2109    -0.933105]
 [  8.67188    6.95313    0.148438   7.80078   13.0859    -4.51563 ]
 ...
 [ -2.92773  -10.6797     1.53711   -1.08301   -0.747559   0.402588]
 [ -3.95703  -12.875     -2.48438   -1.69043   -2.34961   -2.89648 ]
 [ -3.49219  -12.0781    -5.29688   -0.980469  -1.24316   -4.56641 ]]
*****signal_data *****************
[[ -5.60938  -12.8203    -2.73828   -2.47852   -1.5918    -1.60644 ]
 [  0.463379 -11.5469    11.7969     2.875     -0.250977  10.3438  ]
 [ -1.87793  -12.9688     9.63281    0.427002  -1.33887    6.54297 ]
 ...
 [  1.3584    -9.58594   -0.794922   1.14551   -0.141724  -1.09277 ]
 [ -0.686035  -9.49219   -2.10156   -0.71875   -0.040588  -1.91992 ]
 [ -1.72461   -8.5       -2.99805   -1.40625    0.76416   -2.25195 ]]
*****signal_data *****************
[[-2.88281e+00 -9.93750e+00  1.15625e+00 -3.56934e-01  

*****signal_data *****************
[[-0.532715  3.98438   5.15625  -0.107056  0.316162 -2.91211 ]
 [ 0.491943  3.71094   6.4375    0.734375  0.034485 -1.30566 ]
 [ 0.142456  3.91602   6.03906   0.307617  0.192261 -1.36328 ]
 ...
 [ 2.53711  -8.625    -0.57959   2.54688   0.62207  -1.06934 ]
 [ 2.27734  -8.96875  -1.22559   1.83106   0.225586 -1.37305 ]
 [ 0.501465 -9.02344  -2.83398   0.043884  0.138306 -2.38477 ]]
*****signal_data *****************
[[ -0.724121 -14.3359    13.0938     0.852051  -2.44141   10.1094  ]
 [ -3.9707   -15.3438     3.2793    -1.91602   -2.75781    0.240479]
 [ -6.08203  -15.1094    -2.49414   -3.22266   -2.02344   -4.42578 ]
 ...
 [  0.793457 -10.1016     0.828613  -0.928711  -0.295166   1.52637 ]
 [ -1.61523  -10.3984     0.856934  -2.66992   -0.477539   1.24414 ]
 [ -2.73633  -10.5781     0.67041   -3.0332    -0.523926   0.845703]]
*****signal_data *****************
[[ -2.09375  -10.3516     0.378174  -1.91211   -0.235107   0.442871]
 [ -0.795898 -10.4922 

*****signal_data *****************
[[-2.09375   3.5       9.35938   0.286865 -0.081848  0.264648]
 [-2.73633   3.53906   9.50781  -0.283936 -0.034821  0.330322]
 [-3.06641   3.76758   9.71094  -0.491455  0.156006  0.425293]
 ...
 [ 4.60938   3.83008  12.1641    3.39453  -0.850586  2.44336 ]
 [ 4.43359   3.74023  15.1484    2.57422  -0.75293   4.33594 ]
 [ 3.22656   6.10156  15.3438    1.09375   1.28613   3.63086 ]]
*****signal_data *****************
[[  2.35547   -8.69531   -1.6709    -3.39648    0.819336   0.192139]
 [  3.56641  -10.1797     0.742188  -1.74707   -0.531738   2.08398 ]
 [  4.96875  -12.3828     2.17969   -0.275391  -2.1875     2.81641 ]
 ...
 [ -0.125732  -9.9375    -0.76123    0.034088  -0.04007   -0.224243]
 [ -0.245361 -10.        -0.651367  -0.068481  -0.078003  -0.091309]
 [ -0.427246 -10.1719    -0.67041   -0.200317  -0.200317  -0.088379]]
*****signal_data *****************
[[ -0.484863 -10.2344    -0.675293  -0.206299  -0.213867  -0.074524]
 [ -0.54248  -10.2344 

*****signal_data *****************
[[ 4.05762e-01  3.94531e+00  8.42969e+00 -4.04660e-02 -2.55740e-02
  -1.49150e-02]
 [ 3.62793e-01  3.96094e+00  8.45313e+00 -4.68750e-02 -1.17190e-02
  -1.59760e-02]
 [ 4.15283e-01  3.96484e+00  8.59375e+00 -3.40880e-02  1.06510e-02
  -5.32500e-03]
 ...
 [-2.45361e-01 -6.55469e+00  1.80078e+00  5.91309e-01 -1.00684e+00
  -2.40723e-01]
 [-1.30859e+00 -6.66406e+00  8.61816e-01  3.32275e-01  6.87988e-01
  -3.14209e-01]
 [-4.09375e+00 -8.62500e+00 -4.87891e+00 -7.06055e-01 -3.03711e-01
  -1.07605e-01]]
*****signal_data *****************
[[-2.54883e+00 -9.59375e+00 -2.65820e+00 -9.49219e-01 -1.17188e+00
  -5.11470e-02]
 [-1.35156e+00 -9.93750e+00 -1.32617e+00 -5.60547e-01 -1.06348e+00
   1.49150e-02]
 [-2.78809e-01 -1.01797e+01 -1.83887e+00 -4.89990e-01 -8.20310e-02
   1.44897e-01]
 ...
 [ 7.74414e-01  7.93750e+00  5.80859e+00  1.41724e-01  1.32910e+00
   1.78955e-01]
 [-7.52930e-01  7.35938e+00  5.03906e+00  2.13100e-03  1.36523e+00
   1.64062e-01]
 [-8.1

*****signal_data *****************
[[-8.87207e-01 -9.75781e+00 -3.07031e+00  9.59000e-03  4.05762e-01
   1.12915e-01]
 [-8.96484e-01 -9.74219e+00 -2.93945e+00  3.94290e-02  4.81445e-01
   1.01196e-01]
 [-1.02637e+00 -9.67969e+00 -3.08398e+00  3.72920e-02  3.92090e-01
   8.52050e-02]
 ...
 [-1.23281e+01 -1.52109e+01 -2.73828e+00 -2.03516e+00 -6.24023e-01
  -8.31055e-01]
 [-1.06328e+01 -1.39609e+01 -1.14929e-01 -1.78125e+00 -1.45508e+00
  -2.60986e-01]
 [-6.71094e+00 -1.33203e+01 -3.40088e-01 -1.43750e+00 -1.46875e+00
   4.15527e-01]]
*****signal_data *****************
[[ 2.2832   -8.375    -0.981445 -2.24805   1.18945   0.178955]
 [ 1.20508  -7.79688  -1.70019  -1.66406  -0.119324 -0.119324]
 [ 0.367432 -6.11328  -0.728027 -1.40332  -0.888672 -0.312012]
 ...
 [-2.01172  -8.64063  -3.08398  -0.186401 -0.349365 -0.09906 ]
 [-2.04102  -8.71875  -3.23242  -0.12146  -0.477295 -0.111877]
 [-1.96484  -8.96094  -3.42773  -0.063904 -0.627441 -0.114014]]
*****signal_data *****************
[[-1.84

*****signal_data *****************
[[ 7.17285e-01 -1.31797e+01  4.19922e+00  1.89746e+00  3.99414e-01
   5.62500e-01]
 [-1.95508e+00 -1.12500e+01  1.85352e+00  1.77051e+00  1.87988e+00
   6.81641e-01]
 [-1.96875e+00 -1.04922e+01  2.87354e-01  1.95703e+00  2.73047e+00
  -1.07605e-01]
 ...
 [ 3.83398e+00 -1.17109e+01  3.25684e-01 -1.83789e+00 -2.24219e+00
  -5.04883e-01]
 [ 7.12402e-01 -8.53125e+00 -1.10107e-01 -2.16211e+00 -1.55566e+00
  -1.59790e-01]
 [-9.73145e-01 -4.51172e+00 -7.23145e-01 -1.97168e+00 -1.60742e+00
   7.45800e-03]]
*****signal_data *****************
[[-2.32813  -3.45703  -0.914551 -0.981934 -2.21875  -0.102295]
 [-2.00781  -4.73047  -0.852539 -0.527344 -2.03516  -0.184326]
 [-1.18359  -4.91797   0.325684 -0.299316 -1.1875   -0.352539]
 ...
 [ 0.630859 -8.40625  -0.047882  1.66406   1.31152  -0.790527]
 [-0.456055 -8.25      0.229858  1.59277   1.33008  -0.837402]
 [-4.19922  -7.90625   0.953125  0.873535  1.99902  -0.537109]]
*****signal_data *****************
[[-4.31

*****signal_data *****************
[[ 7.68750e+00 -8.09375e+00  7.94922e-01 -1.88599e-01  9.26510e-02
   5.38086e-01]
 [ 7.25391e+00 -7.88672e+00  1.72363e-01 -6.60400e-02  5.73242e-01
   3.17383e-01]
 [ 8.50000e+00 -6.02734e+00 -4.64355e-01  2.55740e-02  5.35645e-01
   4.68750e-02]
 ...
 [-6.95312e-01 -1.08359e+01 -5.31641e+00  1.15723e+00 -2.09839e-01
   2.07764e-01]
 [-1.07813e+00 -1.24531e+01 -5.59766e+00  8.43750e-01  5.64580e-02
   9.58860e-02]
 [-1.39453e+00 -1.31719e+01 -7.24609e+00  2.56836e-01 -2.39624e-01
  -1.06500e-03]]
*****signal_data *****************
[[ -0.623535 -12.1172    -6.3125    -0.210938  -0.827637  -0.148071]
 [ -0.40332  -11.0625    -4.15234   -0.108643  -0.624023  -0.26416 ]
 [ -0.283691 -10.8906    -4.92578    0.012787  -0.479248  -0.188599]
 ...
 [  0.128052  -8.53125   -0.737305  -1.29981   -1.57129   -0.412354]
 [  0.252686  -7.98828   -1.16406   -0.730957  -1.45215   -0.489014]
 [ -0.345947  -6.98438   -1.3457    -0.182129  -1.45606   -0.383545]]
*****s

*****signal_data *****************
[[-2.72852e+00 -1.19700e-03  9.17969e+00  3.46680e-02  1.32202e-01
  -2.17740e-02]
 [-2.71289e+00 -2.99220e-02  9.24219e+00  2.42770e-02  1.47827e-01
  -1.96380e-02]
 [-2.79883e+00 -4.72720e-02  9.34375e+00  2.64130e-02  1.46973e-01
  -1.65860e-02]
 ...
 [-2.90430e+00 -1.28052e-01  9.31250e+00  3.16160e-02  1.43188e-01
  -2.54360e-02]
 [-2.91406e+00 -9.10030e-02  9.27344e+00  3.77200e-02  1.43188e-01
  -2.26900e-02]
 [-2.87305e+00 -5.26730e-02  9.22656e+00  4.13820e-02  1.36841e-01
  -2.23850e-02]]
*****signal_data *****************
[[-2.86719  -0.070618  9.24219   0.033447  0.136475 -0.0233  ]
 [-2.92188  -0.155029  9.32813   0.029465  0.139282 -0.025757]
 [-2.98242  -0.150879  9.38281   0.032532  0.136475 -0.027893]
 ...
 [-2.64648   0.044891  9.17188   0.015114  0.147217 -0.016281]
 [-2.74805  -0.029922  9.27344   0.014503  0.15918  -0.024216]
 [-2.91797  -0.126953  9.4375    0.010834  0.156738 -0.031555]]
*****signal_data *****************
[[-2.96

 [ -0.537109 -10.0781    -2.21484    1.19336    0.60791   -0.403809]]
*****signal_data *****************
[[-1.33984e+00 -1.01875e+01 -4.67578e+00  1.07031e+00  2.01758e+00
  -5.32715e-01]
 [ 9.69850e-02 -1.03359e+01 -2.86523e+00  3.95264e-01  2.82813e+00
  -2.29736e-01]
 [ 2.14063e+00 -9.89844e+00  1.83496e+00 -1.04736e-01  1.45117e+00
  -2.35140e-02]
 ...
 [ 6.33984e+00 -1.60781e+01  6.16406e+00 -7.01172e-01 -7.00684e-01
   7.52441e-01]
 [ 5.63281e+00 -1.49531e+01  3.38135e-01  4.41162e-01  4.27600e-03
   9.40550e-02]
 [ 3.88086e+00 -1.49141e+01 -8.99219e+00  3.66455e-01  4.76562e-01
  -9.71070e-02]]
*****signal_data *****************
[[ 2.59180e+00 -6.19922e+00  4.24609e+00  1.45996e-01  2.77734e+00
   5.79590e-01]
 [ 1.49023e+00 -8.22656e+00  4.41797e+00  1.10644e+00  1.67285e+00
   6.70898e-01]
 [ 1.93066e+00 -9.46875e+00  5.23828e+00  1.22656e+00  4.27979e-01
   9.49219e-01]
 ...
 [ 9.25293e-01 -9.82813e+00  1.33496e+00  5.06900e-02  2.68710e-02
  -4.88700e-03]
 [ 9.98535e-01 -9.7

*****signal_data *****************
[[-0.331543 -9.96875   1.03027   0.087036  0.051575  0.060547]
 [-0.304688 -9.94531   0.869629  0.108459  0.039948  0.058411]
 [-0.048492 -9.96875   0.949707  0.102051  0.06134   0.055054]
 ...
 [ 1.72656  -7.39453   1.40918   0.57959   3.22656   0.332764]
 [ 1.66211  -8.44531   1.13184   0.773438  3.80664   0.209595]
 [ 0.782715 -8.95313   0.959473  0.501465  3.53125   0.491455]]
*****signal_data *****************
[[ 0.163452  5.91406   7.26563   0.039368  0.082581 -0.446533]
 [ 0.235229  6.00781   6.99609   0.088989  0.139771 -0.571777]
 [ 0.180176  5.92578   7.23828   0.027115  0.046722 -0.264404]
 ...
 [-1.08887  -1.58691  10.0391   -1.46875  -2.91016   0.380127]
 [-0.867676 -1.85742  10.0469   -0.79541  -3.02344   0.342773]
 [ 0.706055  3.24805   3.10742   0.946289  1.04981  -5.19531 ]]
*****signal_data *****************
[[ -0.909668   0.275391  10.2344    -0.535645  -1.53809    1.5459  ]
 [ -3.75781   -3.82617   13.8828    -2.70703   -4.51172   

*****signal_data *****************
[[ 3.16602e+00 -7.63672e+00 -4.76172e+00  9.22852e-01 -9.36035e-01
  -1.36719e+00]
 [ 3.66406e+00 -7.92578e+00 -4.52344e+00  1.13672e+00 -9.80469e-01
  -9.02344e-01]
 [ 4.05859e+00 -8.53906e+00 -4.05859e+00  1.22461e+00 -1.27246e+00
  -3.52295e-01]
 ...
 [ 4.36719e+00 -9.03906e+00 -1.67383e+00  1.92505e-01 -1.12671e-01
   3.98926e-01]
 [ 4.34375e+00 -9.06250e+00 -1.64746e+00  1.36841e-01 -1.03577e-01
   3.39844e-01]
 [ 4.12500e+00 -9.11719e+00 -1.98731e+00 -6.53080e-02 -1.28296e-01
   3.52000e-04]]
*****signal_data *****************
[[ 3.97852e+00 -9.10156e+00 -2.22461e+00 -1.71021e-01 -9.35670e-02
  -1.89331e-01]
 [ 3.99805e+00 -9.07031e+00 -2.19727e+00 -1.21460e-01 -4.51660e-02
  -1.29883e-01]
 [ 3.85547e+00 -9.08594e+00 -2.35156e+00 -2.10693e-01 -5.38640e-02
  -2.27051e-01]
 ...
 [ 2.59961e+00 -9.45313e+00 -1.80371e+00 -4.06490e-02 -1.32900e-02
  -1.01501e-01]
 [ 2.57617e+00 -9.42969e+00 -1.75391e+00 -5.07200e-02  5.16900e-03
  -4.14730e-02]
 [ 2.5

*****signal_data *****************
[[ 2.58984e+00  6.80176e-01  9.53125e+00  7.24490e-02  1.00647e-01
   5.19100e-02]
 [ 2.56250e+00  4.21387e-01  9.36719e+00 -4.98600e-03 -1.82983e-01
  -5.69460e-02]
 [ 2.88672e+00  3.75977e-01  9.50000e+00  2.19116e-01 -2.26929e-01
   5.50840e-02]
 ...
 [ 7.85156e-01  2.28320e+00  7.23047e+00  1.05371e+00 -3.90381e-01
  -1.15527e+00]
 [ 1.63769e+00  1.91504e+00  6.67188e+00  1.52539e+00 -6.07422e-01
  -1.37109e+00]
 [ 1.86719e+00  1.65234e+00  6.43750e+00  1.40430e+00 -6.96289e-01
  -1.28613e+00]]
*****signal_data *****************
[[-0.072998  8.41406   7.10547   1.89844  -0.789551  6.76563 ]
 [ 0.243042  8.55469   0.833008  2.13867  -0.693359  1.63379 ]
 [ 0.583008  9.05469  -4.33203   2.3457   -0.284668 -2.30859 ]
 ...
 [-1.81641   9.54688  -0.095764 -0.372803 -0.131592 -0.164917]
 [-1.80176   9.49219  -0.196289 -0.365234 -0.174194 -0.257324]
 [-1.60547   9.42969  -0.148438 -0.207031 -0.227417 -0.238281]]
*****signal_data *****************
[[-1.35

*****signal_data *****************
[[ 9.08691e-01  8.46875e+00  4.85156e+00  8.95508e-01  2.89063e+00
   1.06445e+00]
 [ 1.24414e+00  1.38828e+01  6.62891e+00  9.84375e-01  6.64844e+00
   2.27344e+00]
 [ 1.13379e+00  1.82656e+01  1.19297e+01  6.99219e-01  8.82031e+00
   6.05859e+00]
 ...
 [-3.22021e-01  9.61719e+00  8.14210e-02  6.55520e-02 -1.38850e-02
   2.59250e-02]
 [-3.45947e-01  9.63281e+00  5.26730e-02  3.32950e-02  3.84000e-04
  -2.23900e-03]
 [-2.88574e-01  9.57031e+00  9.57500e-03  7.26320e-02 -5.33140e-02
  -3.62550e-02]]
*****signal_data *****************
[[-0.298096  9.51563   0.210693  0.050415 -0.084778  0.131836]
 [-0.19751   9.69531   0.378174  0.120789  0.073914  0.239624]
 [-0.144897  9.78125   0.291992  0.138794  0.128052  0.122681]
 ...
 [ 3.58008   3.39063  -0.689453  2.59375  -3.00586  -1.01367 ]
 [ 2.63672   4.03516   0.493164  1.32031  -1.88769   0.135254]
 [ 0.649902  3.48047   3.81641  -0.533203 -1.9541    2.76758 ]]
*****signal_data *****************
[[-9.49

*****signal_data *****************
[[-6.23535e-01 -1.01563e+01  1.04981e+00 -5.38574e-01  3.18300e-02
  -3.73291e-01]
 [-5.45410e-01 -1.00000e+01  1.12793e+00 -3.67920e-01  1.51001e-01
  -2.35840e-01]
 [-4.86328e-01 -9.92188e+00  1.54004e+00 -2.47314e-01  1.83594e-01
   1.40747e-01]
 ...
 [ 2.90625e+00 -8.85938e+00  3.93359e+00  1.61865e-01  1.36523e+00
   1.22949e+00]
 [ 2.75000e+00 -8.70313e+00  5.32422e+00  4.00500e-03  1.21777e+00
   2.09766e+00]
 [ 2.80859e+00 -8.68750e+00  5.50391e+00  5.02620e-02  9.90234e-01
   1.81934e+00]]
*****signal_data *****************
[[ 2.73047e+00 -8.92188e+00  4.46094e+00 -2.25520e-02  6.03516e-01
   6.24023e-01]
 [ 2.39648e+00 -9.25000e+00  3.16797e+00 -2.84668e-01  2.16309e-01
  -5.36621e-01]
 [ 1.82813e+00 -9.92188e+00  1.32422e+00 -6.82617e-01 -3.60596e-01
  -1.90430e+00]
 ...
 [-3.09814e-01 -1.01172e+01  1.71680e+00 -5.97168e-01  1.24050e-02
   2.27173e-01]
 [-4.86328e-01 -1.01172e+01  1.54004e+00 -6.19141e-01  9.92600e-03
   4.04660e-02]
 [-5.6

*****signal_data *****************
[[-1.76074e+00 -1.18203e+01  4.36328e+00 -2.12695e+00 -4.91211e-01
   8.79883e-01]
 [-7.80762e-01 -1.10156e+01  3.52148e+00 -9.17480e-01  2.50244e-01
   2.93880e-02]
 [ 2.22070e+00 -1.05859e+01 -2.12695e+00  1.66699e+00  5.45410e-01
  -4.49609e+00]
 ...
 [ 7.69043e-01 -9.53125e+00  1.22656e+00 -1.22986e-01  3.99902e-01
  -2.11940e-02]
 [ 8.08105e-01 -9.64844e+00  1.57910e+00 -6.70170e-02  2.25708e-01
   2.65381e-01]
 [ 8.86719e-01 -9.89844e+00  1.85449e+00  9.14800e-03 -2.33610e-02
   4.32129e-01]]
*****signal_data *****************
[[  1.10254  -10.2969     1.73633    0.179932  -0.33252    0.251465]
 [  1.04394  -10.4531     1.1875     0.096863  -0.391602  -0.238159]
 [  0.827637 -10.2578     0.540039  -0.095093  -0.156372  -0.708496]
 ...
 [ -1.33008  -10.8047    -1.99023   -2.50195    0.777832  -4.26953 ]
 [ -2.01563   -9.41406   -4.32422   -2.55078    1.73633   -5.28516 ]
 [ -0.643066  -9.76563   -3.85352   -0.941895   1.10644   -3.85156 ]]
*****s

*****signal_data *****************
[[ 2.98242e+00 -8.78125e+00  3.93164e+00 -1.46180e-02  9.32617e-01
   3.53711e+00]
 [ 2.12500e+00 -8.95313e+00  4.50000e+00 -6.97266e-01  6.07910e-01
   3.28711e+00]
 [ 1.67481e+00 -8.81250e+00  2.53320e+00 -9.17969e-01  5.97656e-01
   1.05469e+00]
 ...
 [-3.41064e-01  3.01758e+00  8.97656e+00 -8.57422e-01 -7.01172e-01
   1.86400e-03]
 [-1.16089e-01  2.82031e+00  7.14453e+00 -5.39551e-01 -7.98828e-01
  -1.49707e+00]
 [ 8.02000e-02  2.35156e+00  5.64844e+00 -3.22266e-01 -1.20313e+00
  -2.68359e+00]]
*****signal_data *****************
[[-6.68750e+00  3.84570e+00  4.25391e+00 -1.41894e+00  9.35547e-01
  -3.03711e+00]
 [-6.79297e+00  4.05859e+00  3.92969e+00 -1.39356e+00  7.61230e-01
  -3.10352e+00]
 [-7.30469e+00  3.72852e+00  4.17969e+00 -1.68457e+00  2.10205e-01
  -2.70117e+00]
 ...
 [-1.01563e+00 -9.64063e+00  1.71143e-01  1.06050e-02  3.16406e-01
  -6.50020e-02]
 [-1.42285e+00 -1.05156e+01  3.33740e-01 -3.16895e-01 -4.47510e-01
   7.81250e-02]
 [-1.4

*****signal_data *****************
[[-4.70703  -1.64063   0.602051 -0.476318  2.97852   2.32422 ]
 [-3.39453  -3.1543    4.42578   0.669922  1.17188   4.91797 ]
 [-2.02734  -5.70703   8.82813   1.62891  -1.10547   7.45703 ]
 ...
 [-1.23144   3.61719   8.50781   0.093323  0.098877 -0.444824]
 [-0.919922  3.46875   8.94531   0.236572  0.030838 -0.128784]
 [-0.965332  3.28125   9.42188   0.073975 -0.057037  0.21167 ]]
*****signal_data *****************
[[-8.59863e-01  3.38477e+00  9.58594e+00  4.87980e-02  5.66710e-02
   2.45972e-01]
 [-8.74512e-01  3.36328e+00  9.91406e+00 -1.48470e-02  9.59470e-02
   4.65820e-01]
 [-7.21191e-01  3.16992e+00  9.97656e+00  5.71590e-02 -3.53090e-02
   4.71436e-01]
 ...
 [ 1.08984e+00 -1.70156e+01 -2.21313e-01  1.46387e+00 -4.38281e+00
  -5.94238e-01]
 [ 1.99219e+00 -1.45703e+01  1.68359e+00  1.89258e+00 -1.55469e+00
   1.04785e+00]
 [ 1.31738e+00 -1.34453e+01  3.06250e+00  9.74609e-01 -3.42041e-01
   1.94141e+00]]
*****signal_data *****************
[[ 0.19

*****signal_data *****************
[[-2.60352e+00 -1.41328e+01  3.56836e+00 -3.63672e+00 -5.34668e-01
   1.20898e+00]
 [-9.38965e-01 -1.48438e+01 -1.60938e+00 -1.57715e+00 -9.96582e-01
  -3.17578e+00]
 [-1.41016e+00 -1.74063e+01 -1.91797e+00 -1.63867e+00 -2.85352e+00
  -2.78711e+00]
 ...
 [ 1.30493e-01  3.85547e+00  8.58594e+00  2.25830e-01  6.86040e-02
  -1.42090e-01]
 [ 2.26196e-01  3.87305e+00  8.72656e+00  2.57324e-01  6.82370e-02
  -4.59700e-03]
 [ 1.71143e-01  3.81836e+00  8.91406e+00  1.61743e-01  1.05900e-02
   1.49414e-01]]
*****signal_data *****************
[[-2.53906e+00 -1.11016e+01  6.17578e+00  3.71338e-01 -9.62402e-01
   9.78027e-01]
 [-1.67578e+00 -1.12656e+01  7.99609e+00  6.89941e-01 -4.33838e-01
   1.48340e+00]
 [-1.22852e+00 -1.09453e+01  7.51953e+00  5.12695e-01  1.41200e-03
   1.80908e-01]
 ...
 [-3.69629e-01 -1.05391e+01 -2.03906e+00  3.42041e-01 -8.15600e-03
  -1.11938e-01]
 [-5.99121e-01 -1.02031e+01 -2.16406e+00 -2.08280e-02  2.04834e-01
  -1.08337e-01]
 [-1.0

*****signal_data *****************
[[ -9.32813   -0.506348   1.67773   -0.03714    0.079285   0.447266]
 [ -9.54688   -0.564941   1.75586   -0.202271   0.016342   0.42041 ]
 [ -9.28906   -0.663086   1.67773    0.042145  -0.065369   0.273682]
 ...
 [-10.9375     1.57227    5.54297   -1.98633    0.549805   3.00586 ]
 [-11.8203     1.47461    6.54297   -2.29492    0.361328   3.20508 ]
 [-13.2734     1.49414    6.36328   -2.99805    0.304688   2.42383 ]]
*****signal_data *****************
[[-8.40625e+00  1.33691e+00 -2.14648e+00  2.94922e-01  2.25220e-01
  -1.46777e+00]
 [-9.09375e+00  6.70410e-01 -2.97070e+00 -3.13232e-01 -3.53271e-01
  -1.83398e+00]
 [-9.42969e+00  4.15527e-01 -2.57813e+00 -5.17578e-01 -4.86572e-01
  -1.15332e+00]
 ...
 [-9.31250e+00  1.00391e+00  3.04688e-01 -2.12550e-02 -7.14000e-04
  -4.77910e-02]
 [-9.27344e+00  1.04297e+00  2.65381e-01  1.43660e-02  3.08070e-02
  -6.96410e-02]
 [-9.27344e+00  1.10156e+00  3.24219e-01  1.14970e-02  7.17160e-02
  -8.62100e-03]]
*****s

*****signal_data *****************
[[-1.65234e+00 -9.92969e+00  1.83594e+00  1.27246e+00 -5.72266e-01
  -7.34250e-02]
 [-8.80859e-01 -8.71875e+00 -7.90625e+00  1.53711e+00 -1.83300e-03
   1.57227e-01]
 [-5.52246e-01 -8.52344e+00 -5.48047e+00  1.03027e+00 -2.97119e-01
   1.07727e-01]
 ...
 [-1.04688e+00 -1.02891e+01  2.24487e-01 -1.87378e-01 -2.29126e-01
  -5.78310e-02]
 [-1.14941e+00 -1.02578e+01  1.01135e-01 -1.43433e-01 -3.00537e-01
  -6.21030e-02]
 [-1.13184e+00 -1.00625e+01  4.77051e-01 -1.37329e-01 -3.58643e-01
  -1.68910e-02]]
*****signal_data *****************
[[ 2.09500e-02 -8.82813e+00 -1.97852e+00 -3.20740e-02  2.62600e-02
   1.13037e-01]
 [ 2.00586e+00 -1.27734e+01 -5.95313e+00  1.52710e-01  2.81494e-01
   1.22200e-03]
 [ 1.91602e+00 -1.67031e+01 -6.58984e+00 -1.78345e-01  1.09668e+00
  -1.91162e-01]
 ...
 [ 1.15625e+00 -9.60156e+00 -1.84473e+00  7.44629e-01  6.95801e-01
  -7.02510e-02]
 [ 6.60156e-01 -9.38281e+00 -5.76563e+00  7.78320e-01  7.39258e-01
  -9.10030e-02]
 [-6.8

*****signal_data *****************
[[ 4.35791e-01 -8.57031e+00  2.09570e+00  2.14844e+00  1.23047e+00
   1.21289e+00]
 [ 1.09668e+00 -7.93359e+00  1.71875e+00  2.24805e+00  1.49023e+00
   6.69922e-01]
 [ 1.16113e+00 -8.13281e+00  2.21680e+00  1.84961e+00  1.03125e+00
   9.34082e-01]
 ...
 [-3.39648e+00 -9.07031e+00 -8.85620e-02  7.43410e-02  2.55430e-02
  -3.75000e-03]
 [-3.35742e+00 -9.08594e+00 -6.94580e-02  9.20410e-02  8.94200e-03
   1.23210e-02]
 [-3.39063e+00 -9.13281e+00 -4.55020e-02  4.68140e-02 -2.92360e-02
   2.90070e-02]]
*****signal_data *****************
[[-2.85156e+00 -9.10938e+00  6.22560e-02  9.22240e-02  1.37451e-01
   1.83110e-02]
 [-2.73438e+00 -9.22656e+00  7.18300e-03  1.67603e-01  1.61440e-02
  -2.94040e-02]
 [-2.67383e+00 -9.33594e+00  2.39410e-02  1.82007e-01 -7.51950e-02
  -1.01170e-02]
 ...
 [-9.17969e+00 -1.12549e-01  4.76953e+00 -3.70850e-01  1.33789e-01
  -1.50098e+00]
 [-8.67188e+00  4.07100e-02  4.91406e+00  1.07422e-01  2.29614e-01
  -1.08594e+00]
 [-7.6

(519, 6, 1024, 1)
(519, 1024)
(58, 6, 1024, 1)
(58, 1024)


In [41]:
# Training Parameters
learning_rate = 0.00001
num_steps = 5 # ATTENTION INITIALEMENT 150
batch_size = 32
display_step = 1
data_len = len(train_data)

# tf Graph input
X = tf.placeholder(tf.float32, [None, 6, 1024, 1])
Y = tf.placeholder(tf.float32, [None, 1024])

def cross_entropy(y_,output_map):
    return -tf.reduce_mean(y_*tf.log(tf.clip_by_value(output_map,1e-10,1.0))+(1-y_)*tf.log(tf.clip_by_value(1-output_map,1e-10,1.0)), name="cross_entropy")

# Create model
def conv_net(x):
    x = tf.pad(x, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv1_1 = tf.layers.conv2d(x, 64, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
    conv1_1 = tf.pad(conv1_1, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv1_2 = tf.layers.conv2d(conv1_1, 64, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)

    
    conv2_1 = tf.layers.max_pooling2d(conv1_2, pool_size=[1, 2], strides=[1, 2], padding='valid')
    conv2_1 = tf.pad(conv2_1, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv2_2 = tf.layers.conv2d(conv2_1, 128, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
    conv2_2 = tf.pad(conv2_2, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv2_3 = tf.layers.conv2d(conv2_2, 128, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
    
    conv3_1 = tf.layers.max_pooling2d(conv2_3, pool_size=[1, 2], strides=[1, 2], padding='valid')
    
    conv3_1 = tf.pad(conv3_1, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv3_2 = tf.layers.conv2d(conv3_1, 256, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
    conv3_2 = tf.pad(conv3_2, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv3_3 = tf.layers.conv2d(conv3_2, 256, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
    conv3_3 = tf.pad(conv3_3, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv3_4 = tf.layers.conv2d(conv3_3, 256, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
   
    
    conv2_4_1 = tf.layers.conv2d_transpose(conv3_4, 128, kernel_size=[1, 2], strides=[1, 2], padding="VALID")
    conv2_4 = tf.concat([conv2_4_1, conv2_3], axis=3)
    conv2_4 = tf.pad(conv2_4, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv2_5 = tf.layers.conv2d(conv2_4, 128, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
    conv2_5 = tf.pad(conv2_5, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv2_6 = tf.layers.conv2d(conv2_5, 128, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
    
    conv1_3_1 = tf.layers.conv2d_transpose(conv2_6, 64, kernel_size=[1, 2], strides=[1, 2], padding="VALID")
    conv1_3 = tf.concat([conv1_2, conv1_3_1], axis=3)
    conv1_3 = tf.pad(conv1_3, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv1_4 = tf.layers.conv2d(conv1_3, 64, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
    conv1_4 = tf.pad(conv1_4, paddings=[[0, 0], [0, 0], [7, 8], [0, 0]], mode="REFLECT")
    conv1_4 = tf.layers.conv2d(conv1_4, 64, kernel_size=[1, 16], padding='valid', activation=tf.nn.relu)
    conv1_5 = tf.layers.conv2d(conv1_4, 256, kernel_size=[6, 1], padding='valid', activation=tf.nn.relu)
    conv1_6 = tf.layers.conv2d(conv1_5, 1, kernel_size=[1, 1], padding='valid', activation=tf.nn.sigmoid)
    
    out = tf.reshape(conv1_6, [-1, 1024])
    return out

# Construct model
logits = conv_net(X)

# Define loss and optimizer
loss_op = cross_entropy(Y, logits)
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
train_op = optimizer.minimize(loss_op)


# Evaluate model
pred = tf.greater(logits, 0.5)
pred = tf.cast(pred, tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(pred, Y), tf.float32))

# Initialize the variables (i.e. assign their default value)
init = tf.global_variables_initializer()
# Start training


In [42]:
sess = tf.Session()

# Run the initializer
sess.run(init)

for step in range(1, num_steps+1):
    np.random.seed(step)
    indices = np.arange(train_data.shape[0])
    np.random.shuffle(indices)
    train_data_new = train_data[indices]
    train_label_new = train_label[indices]

    start_point = 0
    end_point = start_point + batch_size
    while(end_point < data_len):
        batch_x = train_data_new[start_point: end_point]
        batch_y = train_label_new[start_point: end_point]

        start_point += batch_size
        end_point += batch_size

        # Run optimization op (backprop)
        sess.run(train_op, feed_dict={X: batch_x, Y: batch_y})
        if step % display_step == 0 or step == 1:
            # Calculate batch loss and accuracy
            loss, acc = sess.run([loss_op, accuracy], feed_dict={X: batch_x,
                                                                 Y: batch_y})
            print("Step " + str(step) + ", Minibatch Loss= " + \
                  "{:.4f}".format(loss) + ", Training Accuracy= " + \
                  "{:.3f}".format(acc))
#                 print("Testing Accuracy:", \
#                         sess.run(accuracy, feed_dict={X: test_data[:128],
#                                                       Y: test_label[:128]}))
    print('***********************')
    print("Testing Accuracy:", \
                    sess.run(accuracy, feed_dict={X: test_data,
                                                  Y: test_label}))
    print('***********************')

print("Optimization Finished!")
#sess.close()

Step 1, Minibatch Loss= 0.6915, Training Accuracy= 0.602
Step 1, Minibatch Loss= 0.6923, Training Accuracy= 0.561
Step 1, Minibatch Loss= 0.6905, Training Accuracy= 0.606
Step 1, Minibatch Loss= 0.6906, Training Accuracy= 0.613
Step 1, Minibatch Loss= 0.6910, Training Accuracy= 0.599
Step 1, Minibatch Loss= 0.6877, Training Accuracy= 0.655
Step 1, Minibatch Loss= 0.6850, Training Accuracy= 0.657
Step 1, Minibatch Loss= 0.6877, Training Accuracy= 0.629
Step 1, Minibatch Loss= 0.6865, Training Accuracy= 0.626
Step 1, Minibatch Loss= 0.6858, Training Accuracy= 0.616
Step 1, Minibatch Loss= 0.6897, Training Accuracy= 0.555
Step 1, Minibatch Loss= 0.6847, Training Accuracy= 0.626
Step 1, Minibatch Loss= 0.6825, Training Accuracy= 0.675
Step 1, Minibatch Loss= 0.6796, Training Accuracy= 0.651
Step 1, Minibatch Loss= 0.6821, Training Accuracy= 0.628
Step 1, Minibatch Loss= 0.6790, Training Accuracy= 0.722
***********************
Testing Accuracy: 0.67576444
***********************
Step 2, Min

In [74]:
# Cf https://stackoverflow.com/questions/1987694/how-to-print-the-full-numpy-array-without-truncation
np.set_printoptions(threshold=np.inf) 

predict_data_path = "C:\\Users\\tpailhas\\MIASHS\\TER\\Parkinson\\Dataset\\Gait-Datasets-TIFS20\\Dataset7\\predict\\data"
predict_label_path = "C:\\Users\\tpailhas\\MIASHS\\TER\\Parkinson\\Dataset\\Gait-Datasets-TIFS20\\Dataset7\\predict\\label"
predict_data = read_data(predict_data_path).transpose(0, 2, 3, 1) # 519
predict_label = read_label(predict_label_path)

predicted_data = sess.run(pred, feed_dict={X: predict_data})
# save to a csv file
#np.savetxt(os.path.join(predict_data_path, 'predicted_data.txt'), predicted_data, newline='\r\n') # enregistre sur une seule ligne
# Cf https://stackoverflow.com/questions/22118648/how-to-write-a-numpy-matrix-in-a-text-file-python
with open(os.path.join(predict_data_path, 'predicted_data.txt'),'wb') as f:
    for line in predicted_data:
        np.savetxt(f, line, fmt='%.0f')

print('***********************************************')
print("Testing Accuracy for predict data:", \
      sess.run(accuracy, feed_dict={X: predict_data,Y: predict_label}))
print('***********************************************')
      
#predicted_results = conv_net(predict_data) # returns probability between 0-1. 
#print(predicted_results) # Tensor("Reshape_4:0", shape=(1, 1024), dtype=float64)

#predicted_class =  tf.greater(predicted_results, 0.5) # To get class 0 or 1. Give 1 if probability is greater that 50% else 0.
#print(predicted_class) # Tensor("Greater_4:0", shape=(1, 1024), dtype=bool)

***********************************************
Testing Accuracy for predict data: 0.6279297
***********************************************


In [7]:
#sess.close()